Formulation of the problem and input examples
kirillkuks/sem_gap_big pull request #1
Opened 2022-02-11 19:23 UTC by kirillkuks

2022-02-21 19:58 UTC, DariaWelt requested changes
👍

2022-02-21 20:05 UTC, DariaWelt requested changes
Дополнительно много опечаток в постановке задачи, пожалуйста, вычитайте ее и исправьте.

2022-02-21 20:05 UTC, DariaWelt commented on README.md
> +    * На фотографии не должно быть пересвеченных и тёмных областей.
Мне кажется, лучше изменить требование так, чтобы оно стало измеримым. Обычно о пересветах и потере информации в тенях судят по гистограмме. Может, сюда подойдет условие на вид гистограммы. Например, ограничение на долю пикселей с значениями >225 и <25. Или, может, будет полезно ограничение на градиент на границе

2022-02-21 20:05 UTC, DariaWelt commented on images/examples/DESCRIPTION.md
> +    * [Много маленьких предметов, которые не поместятся в большой многоугольник](https://github.com/kirillkuks/sem_gap_big/blob/develop/images/examples/not_fit/18.jpg)
Отдельно хочется похвалить подготовленные данные! И также обоснование репрезентативности примеров

2022-02-21 20:05 UTC, DariaWelt commented on README.md
> +    Высота предметов не более 4 см.
В таком случае нужен параметр: количество сантиметров в одном пикселе. Или же необходимо задать величину в пикселях. Также может оказаться полезным ограничение на ширину предметов, так как предмет может быть очень узким, или занимать малую долю пикселей, так что его граница станет неразличима.

2022-02-22 16:12 UTC, derkanw commented on images/examples/DESCRIPTION.md
> +    * [Много маленьких предметов, которые не поместятся в большой многоугольник](https://github.com/kirillkuks/sem_gap_big/blob/develop/images/examples/not_fit/18.jpg)
Полностью поддерживаю!) Достаточно легко восстановить исходную идею изображения всего лишь по описанию

2022-02-22 16:15 UTC, derkanw commented on README.md
> +
Возможно, не хватает ввода требования о том, что все предметы на изображении должны быть расположены полностью. Если, конечно, не будет рассматриваться обработка случая, в котором видна только часть предмета

2022-02-26 17:31 UTC, eugenepriymak commented
Возможно ли самопересечение рёбер многоугольника? Например, как показано стрелкой:
![self-intersection](https://user-images.githubusercontent.com/41269755/155853052-3f9ed089-c0c0-4882-ab37-eef90fcab85f.png)

На фотографию объект должен попадать целиком, или может быть видна только часть объекта?

2022-03-17 19:29 UTC, kirillkuks commented on README.md
> +
Добавил такое требование

2022-03-17 19:30 UTC, kirillkuks commented on README.md
> +    Высота предметов не более 4 см.
Задал ограничение на ширину предметов

2022-03-17 19:32 UTC, kirillkuks commented
> Возможно ли самопересечение рёбер многоугольника? Например, как показано стрелкой: ![self-intersection](https://user-images.githubusercontent.com/41269755/155853052-3f9ed089-c0c0-4882-ab37-eef90fcab85f.png)
> 
> На фотографию объект должен попадать целиком, или может быть видна только часть объекта?

Указал требование, что многоугольник должен быть выпуклым

2022-03-17 19:33 UTC, merged